platform :ios,'6.1'
#pod 'Watt', {:git => 'https://github.com/benoit-pereira-da-silva/Watt.git'}

#those dependencies are directly "linked in Watt" when using watt podspec
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SSZipArchive','~> 0.2.2'